kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc-volume
  namespace: "prometheus"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: prometheus-pv-volume
